name: fitness_app_flutter
description: Flutter questionnaire module for FitnessApp
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path: ^1.8.4
  http: ^1.1.0
  url_launcher: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
